#!/usr/bin/env node
/**
 * Auto-generates the GitHub profile README (README.md) from live GitHub data.
 *
 * Run by .github/workflows/stats.yml on a schedule (and on push). It pulls the
 * user's profile + repos, computes top languages by line count, and writes a
 * fresh README.md + assets/banner.svg. Anything you hand-edit in README.md will
 * be overwritten on the next run.
 *
 * Local test (no token needed for public data):
 *   node scripts/generate_readme.mjs
 * In CI it uses $GH_TOKEN (the workflow's GITHUB_TOKEN) for a higher rate limit.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const USER = process.env.README_USER || "ToeKnee-top";
const TOKEN = process.env.GH_TOKEN || null;

const A_HDR = { "User-Agent": "profile-readme-generator" };
if (TOKEN) A_HDR.Authorization = `Bearer ${TOKEN}`;

async function api(path) {
  const r = await fetch(`https://api.github.com${path}`, { headers: A_HDR });
  if (!r.ok) throw new Error(`GET ${path} -> ${r.status}`);
  return r.json();
}

function esc(s) {
  return String(s ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;");
}

const badge = (label, val, color, extra = "") =>
  `https://img.shields.io/badge/${encodeURIComponent(label)}-${encodeURIComponent(String(val)).replace(/-/g, "--")}-${color}${extra}`;

async function main() {
  const [me, repos] = await Promise.all([
    api(`/users/${USER}`),
    api(`/users/${USER}/repos?per_page=100&sort=pushed`),
  ]);

  // ---- top languages by bytes (accurate, not just "dominant language") ----
  const langBytes = {};
  await Promise.all(
    repos.map(async (r) => {
      try {
        const langs = await api(`/repos/${USER}/${r.name}/languages`);
        for (const [l, bytes] of Object.entries(langs)) {
          langBytes[l] = (langBytes[l] || 0) + bytes;
        }
      } catch {}
    })
  );
  const topLangs = Object.entries(langBytes)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 6);
  const totalBytes = topLangs.reduce((s, [, b]) => s + b, 0) || 1;
  const langBar = topLangs
    .map(([l, b]) => {
      const pct = Math.round((b / totalBytes) * 100);
      return `![${l}](https://img.shields.io/badge/${encodeURIComponent(l)}-${pct}25-blue?style=flat-square&logoColor=white)`;
    })
    .join(" ");

  // ---- recent projects (most recently pushed, drop forks, skip this repo) ----
  const recent = repos
    .filter((r) => !r.fork && r.name.toLowerCase() !== USER.toLowerCase())
    .sort((a, b) => new Date(b.pushed_at) - new Date(a.pushed_at))
    .slice(0, 5);

  const totalStars = repos.reduce((s, r) => s + (r.stargazers_count || 0), 0);

  const stats = {
    followers: me.followers,
    following: me.following,
    repos: me.public_repos,
    stars: totalStars,
  };

  // ---- banner SVG (self-contained, GitHub-safe, regenerated live) ----
  const banner = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="840" height="240" viewBox="0 0 840 240">
  <defs>
    <linearGradient id="g" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="#6a5cff"/>
      <stop offset="0.5" stop-color="#9333ea"/>
      <stop offset="1" stop-color="#ec4899"/>
    </linearGradient>
  </defs>
  <rect width="840" height="240" rx="24" fill="url(#g)"/>
  <circle cx="780" cy="30" r="90" fill="#ffffff" opacity="0.08"/>
  <circle cx="60" cy="210" r="70" fill="#000000" opacity="0.10"/>
  <text x="40" y="86" font-family="Segoe UI, Arial, sans-serif" font-size="44" font-weight="700" fill="#ffffff">${esc(me.name || USER)}</text>
  <text x="40" y="122" font-family="Consolas, monospace" font-size="20" fill="#ffffff" opacity="0.85">@${esc(USER)}</text>
  <text x="40" y="164" font-family="Segoe UI, Arial, sans-serif" font-size="16" fill="#ffffff" opacity="0.92">${esc(me.bio || "")}</text>
  <text x="40" y="206" font-family="Segoe UI, Arial, sans-serif" font-size="15" fill="#ffffff" opacity="0.85">${esc(String(stats.repos))} repos · ${esc(String(stats.followers))} followers · ${esc(String(stats.following))} following</text>
</svg>
`;

  // ---- README ----
  const rows = recent.length
    ? recent
        .map(
          (r) =>
            `| [${esc(r.name)}](https://github.com/${USER}/${r.name}) | ${esc(
              (r.description || "").split("\n")[0] || "—"
            )} | ${esc(r.language || "—")} | ![stars](https://img.shields.io/github/stars/${USER}/${r.name}?style=flat-square&label=) |`
        )
        .join("\n")
    : "| _No public projects yet._ | | | |";

  const readme = `<!-- 👋 AUTOMATICALLY GENERATED by ForKie's profile-readme action. Content is overwritten on every run.
     To change what's here, edit scripts/generate_readme.mjs instead. -->
<p align="center">
  <img alt="banner" src="assets/banner.svg" width="840"/>
</p>

<h2 align="center">hey, I'm <b>${esc(me.name || USER)}</b> ✨</h2>

<p align="center">
  ${esc(me.bio || "")}
</p>

<p align="center">
  <a href="https://github.com/${USER}"><img src="${badge("GitHub", USER, "181717")}" alt="GitHub"/></a>
  <a href="https://${esc(me.blog || "")}"><img src="${badge("website", "toeknee.netlify.app", "38bdf8")}" alt="website"/></a>
  <img src="${badge("location", "Houston-Texas", "f59e0b")}" alt="location"/>
</p>

---

## 📊 Stats

<p align="center">
  <img src="${badge("public repos", stats.repos, "6a5cff")}" alt="repos"/>
  <img src="${badge("followers", stats.followers, "6a5cff")}" alt="followers"/>
  <img src="${badge("following", stats.following, "6a5cff")}" alt="following"/>
  <img src="${badge("total⭐", stats.stars, "6a5cff")}" alt="stars"/>
</p>

*Numbers are baked fresh on every workflow run (every 6h by default).*

## 🧰 My Stack

${langBar || "_No public language data yet._"}

**Tools I reach for:** VS Code · GitHub · JavaScript · Node · Slack bots.

## 🚀 Recent Projects

| Project | What it is | Language | ⭐ |
|---|---|---|---|
${rows}

---

<p align="center"><sub>Generated by a GitHub Action on ${new Date().toUTCString()} · <a href=".github/workflows/stats.yml">workflow</a></sub></p>
`;

  writeFileSync(join(ROOT, "README.md"), readme);
  writeFileSync(join(ROOT, "assets", "banner.svg"), banner);

  console.log(
    `Wrote README.md + assets/banner.svg for @${USER} (` +
      `${stats.repos} repos, ${stats.followers} followers, ${stats.following} following, ${stats.stars} stars)`
  );
}

main().catch((e) => {
  console.error(e.message);
  process.exit(1);
});